[primary_masters]
master-1 ansible_host=192.168.11.9

[workers]
worker-1 ansible_host=192.168.11.12
worker-2 ansible_host=192.168.11.13
worker-3 ansible_host=192.168.11.14

[k8s_cluster:children]
primary_masters
; secondary_masters
workers

[primary_masters:vars]
ansible_user=master
ansible_password=12345
ansible_become_pass=12345

; [secondary_masters:vars]
; ansible_user=master
; ansible_password=1234
; ansible_become_pass=1234

[workers:vars]
ansible_user=worker
ansible_password=12345
ansible_become_pass=12345
