; Multi Master Node (GNS3)
[primary_masters]
master-1 ansible_host=192.168.1.33

; [secondary_masters]
; master-2 ansible_host=192.168.122.201
; master-3 ansible_host=192.168.122.202

[workers]
worker-1 ansible_host=192.168.1.22
worker-2 ansible_host=192.168.1.34
worker-3 ansible_host=192.168.1.35

[k8s_cluster:children]
primary_masters
; secondary_masters
workers

[primary_masters:vars]
ansible_user=ubuntu
ansible_password=ubuntu
ansible_become_pass=ubuntu

; [secondary_masters:vars]
; ansible_user=master
; ansible_password=1234
; ansible_become_pass=1234

[workers:vars]
ansible_user=ubuntu
ansible_password=ubuntu
ansible_become_pass=ubuntu