---
- name: Apply Portworx Operator
  become: yes
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: "kubectl apply -f -"
  args:
    stdin: "{{ lookup('file', role_path + '/plugins/portworx/portworx-operator.yml') }}"

- name: Wait for Portworx Operator Pod to be Ready
  become: yes
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: >
    kubectl wait --for=condition=Ready pod 
    -l name=portworx-operator 
    -n px-enterprise 
    --timeout=30s
  register: wait_result
  until: wait_result.rc == 0
  retries: 20
  delay: 2

- name: Apply Portworx Cluster
  become: yes
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: "kubectl apply -f -"
  args:
    stdin: "{{ lookup('file', role_path + '/plugins/portworx/portworx-cluster.yml') }}"
